name: python-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Anaconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Initialize and Activate Conda environment
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda activate fastapi

    - name: Install dependencies
      run: |
        conda install -c conda-forge pytest flake8
        
    - name: Run Flake8
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda activate fastapi
        flake8
        
    - name: Run PyTest
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda activate fastapi
        pytest
