name: python-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Anaconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Initialize and Activate Conda environment
      run: |
        conda init bash
        conda activate fastapi

    - name: Run PyTest
      run: |
        python -m pytest
      env:
        CI: true

    - name: Run Flake8
      run: |
        python -m flake8
