name: python-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Initialize Conda
      run: conda init

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Activate Conda environment
      run: conda activate fastapi

    - name: Run PyTest
      run: |
        python -m pytest
      env:
        CI: true

    - name: Run Flake8
      run: |
        python -m flake8
