name: Python Package using Conda

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Add conda to system path
      run: |
        conda init bash
        source ~/.bashrc  # or source ~/.bash_profile for macOS

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name fastapi-py38
        conda init bash
        conda activate fastapi-py38

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
