name: python-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Jira Login
      uses: atlassian/gajira-login@master
      with:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

    - name: Initialize Conda
      run: conda init bash

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Activate Conda environment
      run: conda activate fastapi

    - name: Run PyTest
      run: |
        python -m pytest
      env:
        CI: true

    - name: Run Flake8
      run: |
        python -m flake8
