name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fastapi
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
